### PR TITLE
Add Eurostat annual energy balances

### PR DESCRIPTION
**Pull request by brynpickering**
For reasons described in this PR's README, we cannot trust the Eurostat dataset download links, as they are not versioned. This starts the process of storing relevant Eurostat datasets in this repo instead. 

The datasets are compressed binaries which obviously is a pain for git versioning, but these files never need decompressing on an individual's device since pandas can load the data into memory directly from the compressed file. `nrg_bal_c.tsv.gz` is 235MB uncompressed, ~20MB compressed. Although git's own compression would manage this compression just as well as gzip, pushing it online isn't possible due to the single file size limit of 100MB (git log recommends git LFS). This pre-compression would only create a larger data footprint than the uncompressed file if we update the version ~10 times. This is unlikely to happen.

### CODE REVIEW

**Comment by suvayu** [comment]
I guess the plan is to have a new entry in the README every time a dataset is added?  I would add a little more info in the entry besides date.  For example in this case it is the last year that includes UK. It is of course deducible after some thought, but having it makes it more friendly.

Maybe follow this recipe:
- responses to "what triggered the update?" can be in the description,
- any gotchas that were found on cursory exploration after downloading this version.
- maybe include the date in the dataset file name? no strong opinion here, just thought I mention this option exists.

Otherwise this looks fine to me.

**Review by suvayu — APPROVED** [review]

**Review by timtroendle — APPROVED** [review]
I am hesitating, because we should try to get rid of this repository rather than adding more data. I know of the problems and likely there is no other way, but just want to make sure there is no other way. For example, did you check if someone else has done this already? Like, has anyone mirrored the data on some version-aware datastore like Zenodo?

One reason why I am saying this is that this repository makes euro-calliope's release process a good bit more complicated. See https://github.com/calliope-project/euro-calliope/pull/191 and https://github.com/calliope-project/euro-calliope/pull/189.

Further, I want to release 1.1. this week (and I hope we can fix the issues with this repo in https://github.com/calliope-project/euro-calliope/pull/191). After I've released it, you can push this to `develop`, rather than the feature branch.

**Comment by brynpickering** [comment]
> For example, did you check if someone else has done this already?

I have checked, with no luck. In my correspondence with the eurostat helpdesk, I asked this very question and didn't get any useful response. A search of zenodo brings up the odd dataset, but mostly pre-processed for some specific study and not comprehensive. It's somewhat understandable, according to [eurostat](https://data.europa.eu/data/datasets/estat-web-services?locale=en) the datasets are updated twice-daily. This would be too much to keep track of in some third-party versioned repo.

I'll wait for v1.1 and then update this PR onto `develop`, along with making the changes @suvayu is looking for.

**Comment by timtroendle** [comment]
Fine with me. About the version: I just pushed the release of euro-calliope v1.1 to October as there are open issues with this dataset repository, I have too many other things to do rn, and there is no real pressure.

**Pull request merged**
