### PR TITLE
Add translation CSVs and README

### PR DESCRIPTION
**Pull request by brynpickering**
These files are already required in the Euro-Calliope `feature-sector-coupling` but seem to not have made it into the `data` directory there. Rather than add them there, it seems to make sense to avoid a `data` directory in Euro-Calliope and add them here directly. This PR will be followed by a matching PR in the Euro-Calliope repo.

### CODE REVIEW

**Review by timtroendle — APPROVED** [review]
I cannot review the content of these files, but adding them in this way makes sense to me.

What about license? See the readme.md in biofuels.

**Comment by brynpickering** [comment]
This is effectively a translation between metadata that I put together, so does it need licensing?

**Comment by timtroendle** [comment]
Have you created these files? I think it should be fine then.

**Comment by brynpickering** [comment]
> Have you created these files?

Yes, I did.

**Pull request merged**
